tangible_objects = [
    # Household Items
    "table",
    "chair",
    "lamp",
    "sofa",
    "television",
    "refrigerator",
    "microwave",
    "bed",
    "wardrobe",
    "toaster",
    "mirror",
    "clock",

    # Kitchen Items
    "fork",
    "knife",
    "spoon",
    "plate",
    "bowl",
    "cup",
    "pot",
    "pan",
    "blender",
    "cutting board",

    # Office Items
    "computer",
    "printer",
    "notebook",
    "pen",
    "pencil",
    "desk",
    "stapler",
    "paper clip",
    "envelope",
    "mouse",
    "keyboard",

    # Personal Items
    "phone",
    "watch",
    "wallet",
    "keys",
    "glasses",
    "backpack",
    "handbag",
    "umbrella",
    "hat",
    "scarf",
    
    # Clothing Items
    "shirt",
    "pants",
    "dress",
    "socks",
    "shoes",
    "jacket",
    "coat",
    "sweater",
    "tie",
    "gloves",
    
    # Tools
    "hammer",
    "screwdriver",
    "wrench",
    "drill",
    "saw",
    "pliers",
    "tape measure",
    "level",
    "chisel",
    "ladder",
    
    # Vehicles
    "car",
    "bicycle",
    "motorcycle",
    "bus",
    "truck",
    "train",
    "airplane",
    "boat",
    "scooter",
    "skateboard",
    
    # Electronics
    "smartphone",
    "tablet",
    "laptop",
    "camera",
    "headphones",
    "speaker",
    "television",
    "game console",
    "remote control",
    "charger",

    # Nature
    "tree",
    "flower",
    "rock",
    "leaf",
    "shell",
    "feather",
    "fruit",
    "vegetable",
    "water bottle",
    "sand",

    # Miscellaneous
    "book",
    "magazine",
    "newspaper",
    "toy",
    "paintbrush",
    "canvas",
    "musical instrument",
    "bicycle helmet",
    "basket",
    "flashlight"

        "vase",
    "curtain",
    "carpet",
    "pillow",
    "blanket",
    "fan",
    "heater",
    "vacuum cleaner",
    "broom",
    "dustpan",
    "mop",
    "ironing board",
    "iron",

    # More Kitchen Items
    "whisk",
    "measuring cup",
    "spatula",
    "tongs",
    "grater",
    "peeler",
    "colander",
    "mixer",
    "food processor",
    "kettle",
    "coffee maker",

    # More Office Items
    "calculator",
    "ruler",
    "highlighter",
    "binder",
    "file folder",
    "clipboard",
    "shredder",
    "whiteboard",
    "projector",
    "phone charger",

    # More Personal Items
    "earrings",
    "necklace",
    "bracelet",
    "ring",
    "sunglasses",
    "camera",
    "lip balm",
    "hairbrush",
    "wallet",
    "water bottle",

    # More Clothing Items
    "blouse",
    "jeans",
    "shorts",
    "skirt",
    "suit",
    "swimsuit",
    "pajamas",
    "robe",
    "belt",
    "slippers",

    # More Tools
    "paint roller",
    "putty knife",
    "adjustable wrench",
    "allen wrench",
    "vise",
    "clamp",
    "hand saw",
    "wire stripper",
    "utility knife",
    "crowbar",

    # More Vehicles
    "sailboat",
    "yacht",
    "submarine",
    "hovercraft",
    "segway",
    "jet ski",
    "snowmobile",
    "golf cart",
    "tractor",
    "hot air balloon",

    # More Electronics
    "smartwatch",
    "e-reader",
    "digital camera",
    "camcorder",
    "GPS device",
    "VR headset",
    "fitness tracker",
    "smart speaker",
    "bluetooth headset",
    "power bank",

    # More Nature
    "acorn",
    "mushroom",
    "pinecone",
    "cactus",
    "fern",
    "lichen",
    "moss",
    "coral",
    "starfish",
    "cobblestone",

    # More Miscellaneous
    "sculpture",
    "trophy",
    "medal",
    "stamp",
    "postcard",
    "scrapbook",
    "model car",
    "kite",
    "yo-yo",
    "board game",
    "puzzle",
    "chess set",
    "fishing rod",
    "camping tent",
    "sleeping bag",
    "binoculars",
    "compass",
    "hiking boots",
    "bicycle pump",
    "first aid kit",


    "apple",
    "banana",
    "orange",
    "grape",
    "watermelon",
    "pineapple",
    "strawberry",
    "blueberry",
    "raspberry",
    "kiwi",
    "mango",
    "pear",
    "peach",
    "plum",
    "cherry",
    "pomegranate",
    "lemon",
    "lime",
    "coconut",
    "apricot",
    "avocado",
    "fig",
    "guava",
    "papaya",
    "passion fruit",
    "dragon fruit",
    "lychee",
    "durian",
    "jackfruit",
    "starfruit",
    "date",
    "olive",
    "blackberry",
    "elderberry",
    "cranberry",
    "persimmon",
    "tangerine",
    "grapefruit",

    # Vegetables
    "carrot",
    "broccoli",
    "cauliflower",
    "spinach",
    "kale",
    "lettuce",
    "cabbage",
    "brussels sprouts",
    "peas",
    "green beans",
    "asparagus",
    "beetroot",
    "radish",
    "turnip",
    "parsnip",
    "potato",
    "sweet potato",
    "yam",
    "pumpkin",
    "squash",
    "cucumber",
    "bell pepper",
    "chili pepper",
    "jalapeno",
    "onion",
    "garlic",
    "ginger",
    "leek",
    "celery",
    "artichoke",
    "eggplant",
    "tomato",
    "mushroom",
    "corn",
    "rhubarb",
    "bok choy",
    "watercress",
    "seaweed",

    # Dairy
    "milk",
    "cheese",
    "butter",
    "yogurt",
    "cream",
    "ice cream",

    # Meats
    "chicken",
    "beef",
    "pork",
    "lamb",
    "duck",
    "turkey",
    "venison",
    "ham",
    "bacon",
    "sausage",
    "salami",
    "steak",
    "ribs",

    # Seafood
    "salmon",
    "tuna",
    "trout",
    "mackerel",
    "sardine",
    "anchovy",
    "cod",
    "haddock",
    "shrimp",
    "prawn",
    "lobster",
    "crab",
    "scallop",
    "clam",
    "oyster",
    "mussel",
    "octopus",
    "squid",
    "cuttlefish",
    "eel",

    # Grains and Legumes
    "rice",
    "quinoa",
    "barley",
    "oats",
    "wheat",
    "cornmeal",
    "couscous",
    "lentils",
    "chickpeas",
    "black beans",
    "kidney beans",
    "pinto beans",
    "navy beans",
    "white beans",
    "red beans",
    "soybeans",
    "edamame",
    "tofu",
   

    # Nuts and Seeds
    "almond",
    "peanut",
    "cashew",
    "walnut",
    "pecan",
    "pistachio",
    "hazelnut",
    "macadamia",
    "brazil nut",
    "chestnut",
    "sunflower seed",
    "pumpkin seed",
    "sesame seed",
    "chia seed",
    "flaxseed",
    "poppy seed",

    # Baked Goods
    "bread",
    "bagel",
    "croissant",
    "bun",
    "roll",
    "muffin",
    "scone",
    "biscuit",
    "cookie",
    "cake",
    "pie",
    "tart",
    "brownie",
    "pancake",
    "waffle",
    "doughnut",
    "pastry",

    # Beverages
    "water",
    "juice",
    "soda",
    "coffee",
    "tea",
    "milkshake",
    "smoothie",
    "lemonade",
    "wine",
    "beer",
    "whiskey",
    "vodka",
    "rum",
    "gin",
    "tequila",
    "brandy",
    "liqueur",
    "champagne",
    "cider",
    "kombucha"
]

myset = set(tangible_objects)

for item in myset:
    print(f'"{item}",')